name: Python CI for TicTacTool

on:
  push:
    branches:
      - main  # Run workflow when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Run workflow for pull requests to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use a Linux environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Pulls the repository's code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.4  # Use Python 3.9 for testing

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || echo "No requirements.txt found, skipping."

    - name: Run unit tests
      run: |
        python -m unittest discover -s . -p "test_*.py"  # Discover and run test files starting with 'test_'
